development:
 adapter: postgresql
 database: library_app
 username: library
 password: library
 host: 127.0.0.1


test:
 adapter: postgresql
 database: library_app_test
 username: library
 password: library
 host: 127.0.0.1
